name: gglandmark
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - astroid=1.6.2
  - ca-certificates=2018.03.07
  - certifi=2018.1.18
  - h5py=2.7.1
  - hdf5=1.10.1
  - intel-openmp=2018.0.0
  - isort=4.3.4
  - lazy-object-proxy=1.3.1
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libprotobuf=3.5.1
  - mccabe=0.6.1
  - mkl=2018.0.2
  - ncurses=6.0
  - numpy=1.12.1
  - openssl=1.0.2o
  - pandas=0.22.0
  - pip=9.0.3
  - protobuf=3.5.1
  - pycodestyle=2.3.1
  - pylint=1.8.3
  - python=3.6.5
  - python-dateutil=2.7.2
  - pytz=2018.3
  - pyyaml=3.12
  - readline=7.0
  - scipy=1.0.1
  - setuptools=39.0.1
  - six=1.11.0
  - sqlite=3.22.0
  - tk=8.6.7
  - werkzeug=0.14.1
  - wheel=0.31.0
  - wrapt=1.10.11
  - xz=5.2.3
  - yaml=0.1.7
  - zlib=1.2.11
  - autopep8=1.3.4
  - pip:
    - absl-py==0.1.13
    - astor==0.6.2
    - bleach==1.5.0
    - gast==0.2.0
    - grpcio==1.10.0
    - html5lib==0.9999999
    - keras==2.1.5
    - markdown==2.6.11
    - pillow==5.1.0
    - tensorboard==1.7.0
    - tensorflow==1.7.0
    - termcolor==1.1.0

